name: Create Azure VM
 
on:
  push:
    branches:
      - main
 
jobs:
  create-vm:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
 
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.MY_SECRET }}
 
    - name: Create Azure VM
      run: |
        # Define variables
        RESOURCE_GROUP="wissen"
        LOCATION="eastus" 
        VM_NAME="MyLinuxVM"
        IMAGE="Ubuntu2204"
        SIZE="Standard_B1s"
 
        # Create VM in the existing resource group
        az vm create \
          --resource-group $RESOURCE_GROUP \
          --name $VM_NAME \
          --image $IMAGE \
          --size $SIZE \
          --admin-username meghana\
          --generate-ssh-keys
